version: '3.7'

services:
  server:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    restart: 'unless-stopped'
    networks:
      - koji-kukac-prod

networks:
  koji-kukac-prod:
    driver: bridge

volumes:
  data:
    driver: local
