version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - koji-kukac-dev
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - koji-kukac-dev

networks:
  koji-kukac-dev:
    driver: bridge

volumes:
  data:
    driver: local
